const express=require('express')
const app =express()
const {SERVERPORT,CLIENT_URL}=require('./constants')
const cookieParser = require('cookie-parser')
const passport = require('passport')
const cors = require('cors')
require('./middleware/passport_middleware.js')
app.use(express.json())
app.use(cookieParser())
app.use(cors({ origin: CLIENT_URL, credentials: true }))
app.use(passport.initialize())
const homeRoutes=require('./routes/home.js')
app.use('/',homeRoutes)
const loginRoutes=require('./routes/login.js')
app.use('/',loginRoutes)
const registerRoutes=require('./routes/register.js')
app.use('/',registerRoutes)
const showdetailsRoutes=require('./routes/showdetails.js')
app.use('/',showdetailsRoutes)
const commentroutes=require('./routes/comment.js')
app.use('/',commentroutes)
const replyroutes=require('./routes/reply.js')
app.use('/',replyroutes)
const getcommentsroutes=require('./routes/getcomments.js')
app.use('/',getcommentsroutes)
const searchproductsroutes=require('./routes/searchproducts.js')
app.use('/',searchproductsroutes)
const showfilteredproductsroutes=require('./routes/showfilteredproducts.js')
app.use('/',showfilteredproductsroutes)
const showmenuproductsroutes=require('./routes/showmenuproducts.js')
app.use('/',showmenuproductsroutes)
const cartroutes=require('./routes/cart.js')
app.use('/',cartroutes)
const cart1routes=require('./routes/cart1.js')
app.use('/',cart1routes)
const paymentroutes=require('./routes/payment.js')
app.use('/',paymentroutes)
const userinfoRoutes=require('./routes/userinfo.js')
app.use('/',userinfoRoutes)
const updateuserinfoRoutes=require('./routes/updateuserinfo.js')
app.use('/',updateuserinfoRoutes)
const addnewproductRoutes=require('./routes/addnewproduct.js')
app.use('/',addnewproductRoutes)
const updateproductRoutes=require('./routes/updateproduct.js')
app.use('/',updateproductRoutes)
const pendingpurachaseRoutes=require('./routes/pendingpurchase.js')
app.use('/',pendingpurachaseRoutes)
const usernotificationRoutes=require('./routes/usernotification.js')
app.use('/',usernotificationRoutes)
const pendingpurchase1Routes=require('./routes/pendingpurchase1.js')
app.use('/',pendingpurchase1Routes)
const reviewRoutes=require('./routes/review.js')
app.use('/',reviewRoutes)
const compareRoutes=require('./routes/compare.js')
app.use('/',compareRoutes)

// server start function
const  appstart=async ()=>{
    try{
       await app.listen(SERVERPORT,()=>{
            console.log(`app is running at ${SERVERPORT}`)
        })
    } catch(err){
        console.log(`faced error : ${err}`)
    }
} 

appstart();
